config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :blogger do 
    resources :comments
  end
  root "blogger#index"
  # post "/add", to:"blogger#add"
  # get "/show",to:"blogger#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_db.rb
class BlogDb < ApplicationRecord
    has_many :comments,dependent: :destroy
    validates :name, presence:true
    validates :article,presence:true ,length:{minimum:10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_db
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogger_controller.rb
class BloggerController<ApplicationController


     http_basic_authenticate_with name: "shekhar", password: "shekhar", except: [:index, :show]

    def index
         @blog = BlogDb.all
    end
     
    def show
         @blog = BlogDb.find(params[:id])
    end

    def new
          @blog=BlogDb.new()
    end

    def create
     @blog = BlogDb.new(blog_params)
   
     # @blog.name=params[:name]
     # @blog.article=params[:article]
          if @blog.save
          redirect_to blogger_url(@blog[:id])
          else
          render :new, status: :unprocessable_entity
          end
     end

     def edit
          @blog=BlogDb.find(params[:id])
     end

     def update
          @blog = BlogDb.find(params[:id])
          puts params
          puts"-------------------------------"
          if @blog.update(blog_params)
            redirect_to blogger_url(@blog[:id])
          else
            render :edit, status: :unprocessable_entity
          end
     end  

     def destroy
          @blog = BlogDb.find(params[:id])
          @blog.destroy
          redirect_to blogger_index_path, status: :see_other
     end
          
     private
     def blog_params  
          params.require(:blog_db).permit(:name,:article)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "shekhar", password: "shekhar", only: :destroy
    def create
        @blog = BlogDb.find(params[:blogger_id])
        @blog = @blog.comments.create(comment_params)
        redirect_to blogger_path(params[:blogger_id])
      end
    
    def destroy
        @blog = BlogDb.find(params[:blogger_id])
        @comment = @blog.comments.find(params[:id])
        @comment.destroy
        redirect_to blogger_path(params[:blogger_id]), status: 303
    end

      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogger/edit.html.erb
<h1>Edit blog</h1>

<%= form_with url: "/blogger/#{@blog[:id]}", method: :put ,model: @blog do |form| %>
 <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @blog.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :article %><br>
    <%= form.text_area :article %><br>
    <% @blog.errors.full_messages_for(:article).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogger/index.html.erb
<h1>Blog</h1>

<ul>
  <% @blog.each do |b| %>
     <li>
      <%= link_to b.name, blogger_path(b) %>
    </li>
  <% end %>
  <%= link_to "new Blog",new_blogger_path%>
  
</ul>

app/views/blogger/new.html.erb
<h1>New Article</h1>

<%= form_with url:"/blogger" ,method: :post ,model: @blog do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :name %>
    <% @blog.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
      <% end %>
      
  </div>

  <div>
    <%= form.label :article %><br>
    <%= form.text_area :article %>
    <% @blog.errors.full_messages_for(:article).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogger/show.html.erb
<h1><%= @blog.name %></h1>

<p><%= @blog.article %>

<li>
<%= link_to "Edit this blog",edit_blogger_url(@blog[:id])%>
<br>
<li><%= link_to "Destroy", blogger_path(@blog), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure ?"
                  } %></li>

<%=     link_to "all blogs",blogger_index_path%>
</li>
</p>


<h2>Comments</h2>
<% @blog.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  
  <%= link_to "Destroy Comment","/blogger/#{comment[:blog_db_id]}/comments/#{comment[:id]}" , data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>
<% end %>



<h2>Add a comment:</h2>
<%= form_with url:"/blogger/#{@blog[:id]}/comments"  , model: [ @blog, @blog.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>